### ISSUE TITLE
userGroups setting only accepts "full" IDs?

### ISSUE THREAD

**Issue by tomkiss** [verbb/social-login#7]
### Describe the bug

When setting the `userGroups` setting in the config file, it only seems to accept a full/verbose ID (forgive me, unsure of the correct name). 

I've tried:

```php
'userGroups' => ['groupSlug'], // fail
'userGroups' => ['Group Name'], // fail
'userGroups' => [2], // simple ID, fail
'userGroups' => ['2a99c0a5-3066-45dc-8168-ec7572041f2e'], // success!
```
There is no example in the documentation as to how this should work but it seems like perhaps its not meant to work like this?

### Steps to reproduce

1. Create a config file with the `userGroups` option
2. Confirm that only full/verbose IDs work

### Craft CMS version

4.4.9

### Plugin version

1.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
This is correct behaviour, and refers to the UID of a user group. This is because when storing created user groups in project config, the ID isn't retained. This is because it's applied across multiple environments, and they aren't always guaranteed to be the same ID, but the UID will never change.

I've updated the docs with clarification.

**Comment by tomkiss** [comment]
Aha ok, thanks for explaining!
